name: flutter_widget_from_html_core
version: 0.5.0+3
description: Flutter package for widget tree building from html that focuses on correctness and extensibility.
homepage: https://github.com/daohoangson/flutter_widget_from_html/tree/master/packages/core

environment:
  # https://github.com/flutter/flutter/commit/7948a7863bd8931e4e029c5b109f26c1b3dcf8ea
  flutter: ">=1.23.0-4.0.pre <2.0.0"
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  html: ^0.14.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  network_image_mock: ^1.0.1
  pedantic: ^1.9.0
  test: any
